import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import "./buttons.css";
import "./animations.css";
import Navbar from "@/components/S1/Navbar";
import Footer from "@/components/S10/Footer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} font-bold antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
